import { useMemo, useState } from 'react'
import { Check, ChevronLeft, ChevronRight, GripVertical, Plus, Save, Trash2 } from 'lucide-react'
import { useAppStore } from '../stores/appStore'
import { createId } from '../utils/ids'
import type { QuestionPaper } from '../types'

const steps=['Exam Information','Questions','Arrangement','Design','Preview'] as const
const empty=():QuestionPaper=>{const now=new Date().toISOString();return{id:createId('paper'),name:'Untitled Paper',institutionName:'',examName:'',className:'',subject:'',academicYear:'',examDate:'',time:'',fullMarks:100,teacherName:'',instructions:'',questionIds:[],sections:[],template:'classic',status:'draft',createdAt:now,updatedAt:now}}
export function PaperBuilder({onDone}:{onDone:()=>void}){
 const questions=useAppStore(s=>s.questions),addPaper=useAppStore(s=>s.addPaper)
 const [step,setStep]=useState(0),[paper,setPaper]=useState<QuestionPaper>(empty())
 const [selected,setSelected]=useState<string[]>([])
 const selectedQuestions=useMemo(()=>selected.map(id=>questions.find(q=>q.id===id)).filter(Boolean),[selected,questions])
 const total=selectedQuestions.reduce((sum,q)=>sum+(q?.marks??0),0)
 const patch=(x:Partial<QuestionPaper>)=>setPaper(p=>({...p,...x,updatedAt:new Date().toISOString()}))
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])
 const save=()=>{patch({questionIds:selected});addPaper({...paper,questionIds:selected,updatedAt:new Date().toISOString()});onDone()}
 return <section className="space-y-5">
  <div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Create Question Paper</h2><p className="text-sm text-slate-500">Build a professional paper step by step.</p></div></div>
  <div className="grid grid-cols-5 gap-1 overflow-x-auto">{steps.map((x,i)=><button key={x} onClick={()=>i<=step&&setStep(i)} className={`min-w-[100px] rounded-xl p-3 text-center text-xs ${i===step?'bg-slate-950 text-white dark:bg-white dark:text-slate-950':'bg-slate-100 dark:bg-slate-900'}`}><span className="font-bold">{i+1}</span><p className="mt-1">{x}</p></button>)}</div>
  {step===0&&<Panel title="Exam Information"><div className="grid gap-4 sm:grid-cols-2">{[['institutionName','Institution Name'],['examName','Exam Name'],['className','Class'],['subject','Subject'],['academicYear','Academic Year'],['examDate','Exam Date'],['time','Time'],['teacherName','Teacher Name']].map(([k,l])=><label key={k} className="text-sm">{l}<input value={(paper as never)[k]} onChange={e=>patch({[k]:e.target.value} as Partial<QuestionPaper>)} className="mt-1 min-h-11 w-full rounded-xl border p-2 dark:bg-slate-950"/></label>)}<label className="text-sm">Full Marks<input type="number" value={paper.fullMarks} onChange={e=>patch({fullMarks:Number(e.target.value)})} className="mt-1 min-h-11 w-full rounded-xl border p-2 dark:bg-slate-950"/></label><label className="text-sm sm:col-span-2">Instructions<textarea value={paper.instructions} onChange={e=>patch({instructions:e.target.value})} rows={3} className="mt-1 w-full rounded-xl border p-2 dark:bg-slate-950"/></label></div></Panel>}
  {step===1&&<Panel title="Select Questions"><div className="space-y-2">{questions.map(q=><label key={q.id} className="flex cursor-pointer items-start gap-3 rounded-xl border p-3"><input type="checkbox" checked={selected.includes(q.id)} onChange={()=>toggle(q.id)} className="mt-1 size-4"/><span dir={q.direction} className="min-w-0 flex-1 text-sm">{q.questionText}</span><span className="text-xs text-slate-500">{q.marks} marks</span></label>)}</div></Panel>}
  {step===2&&<Panel title="Arrange Questions"><div className="space-y-2">{selected.map((id,i)=>{const q=questions.find(x=>x.id===id);return <div key={id} className="flex items-center gap-2 rounded-xl border p-3"><GripVertical size={18} className="text-slate-400"/><span className="w-7 text-sm font-bold">{i+1}</span><span dir={q?.direction} className="min-w-0 flex-1 text-sm">{q?.questionText}</span><button disabled={i===0} onClick={()=>{const x=[...selected];[x[i-1],x[i]]=[x[i],x[i-1]];setSelected(x)}} className="grid size-9 place-items-center rounded-lg border disabled:opacity-30">↑</button><button disabled={i===selected.length-1} onClick={()=>{const x=[...selected];[x[i],x[i+1]]=[x[i+1],x[i]];setSelected(x)}} className="grid size-9 place-items-center rounded-lg border disabled:opacity-30">↓</button></div>})}</div></Panel>}
  {step===3&&<Panel title="Paper Design"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{['classic','modern','academic','islamic','minimal','premium'].map(x=><button key={x} onClick={()=>patch({template:x})} className={`rounded-xl border p-5 text-left capitalize ${paper.template===x?'border-slate-950 ring-2 dark:border-white':'border-slate-200 dark:border-slate-800'}`}>{x}</button>)}</div></Panel>}
  {step===4&&<Panel title="Preview"><div className="mx-auto max-w-2xl rounded border bg-white p-6 text-black shadow-sm"><div className="border-b pb-4 text-center"><h3 className="font-bold">{paper.institutionName||'Institution Name'}</h3><p>{paper.examName||'Examination'}</p><p className="text-sm">{paper.subject||'Subject'} · {paper.className||'Class'} · Full Marks: {paper.fullMarks}</p></div><div className="mt-5 space-y-4">{selectedQuestions.map((q,i)=><div key={q!.id} className="flex gap-2"><span className="font-semibold">{i+1}.</span><span dir={q!.direction} className="flex-1">{q!.questionText}</span><span>[{q!.marks}]</span></div>)}</div></div></Panel>}
  <div className="flex flex-wrap items-center justify-between gap-3"><div className={total!==paper.fullMarks?'text-sm text-amber-600':'text-sm text-emerald-600'}>{selected.length} questions · {total} / {paper.fullMarks} marks {total!==paper.fullMarks&&'— marks mismatch'}</div><div className="flex gap-2">{step>0&&<button onClick={()=>setStep(s=>s-1)} className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-4"><ChevronLeft size={17}/>Back</button>}{step<4?<button onClick={()=>setStep(s=>s+1)} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-950 px-5 text-sm font-medium text-white dark:bg-white dark:text-slate-950">Next<ChevronRight size={17}/></button>:<button onClick={save} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-950 px-5 text-sm font-medium text-white dark:bg-white dark:text-slate-950"><Save size={17}/>Save Draft</button>}</div></div>
 </section>
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h3 className="font-semibold">{title}</h3><div className="mt-5">{children}</div></div>}