import type { Question, QuestionPaper } from '../types'
import { defaultNumbering, formatNumber } from '../utils/numbering'
type Template='classic'|'modern'|'academic'|'islamic'|'minimal'|'premium'
const templateClass=(t:string)=>['classic','modern','academic','islamic','minimal','premium'].includes(t)?t:'classic'
export function PaperRenderer({paper,questions}:{paper:QuestionPaper;questions:Question[]}){
 const map=new Map(questions.map(q=>[q.id,q])); const rtl=questions.filter(q=>paper.questionIds.includes(q.id)).filter(q=>q.direction==='rtl').length>paper.questionIds.length/2
 const template=templateClass(paper.template)
 return <article className={`qpg-paper qpg-${template} mx-auto bg-white text-black`} dir={rtl?'rtl':'ltr'}>
  <header className="qpg-paper-header"><div className="qpg-brand-mark" aria-hidden="true">Q</div><h1>{paper.institutionName}</h1><h2>{paper.examName}</h2><div className="qpg-meta"><span>{paper.className}</span><span>{paper.subject}</span><span>{paper.time}</span><span>Full Marks: {paper.fullMarks}</span></div>{paper.instructions&&<p className="qpg-instructions">{paper.instructions}</p>}</header>
  <div className="qpg-paper-body">{paper.sections?.length?paper.sections.map((section,si)=><div key={section.id} className="qpg-section"><h3 className="qpg-section-title">{section.title}</h3>{section.questionIds.map((id,i)=><QuestionView key={id} q={map.get(id)} index={paper.questionIds.indexOf(id)>=0?paper.questionIds.indexOf(id):i}/>)}</div>):paper.questionIds.map((id,i)=><QuestionView key={id} q={map.get(id)} index={i}/>)}</div>
  <footer className="qpg-footer"><span>{paper.institutionName}</span><span>Page <span className="page-number"/></span></footer>
 </article>
}
function QuestionView({q,index}:{q:Question|undefined;index:number}){if(!q)return null;return <section className="qpg-question" dir={q.direction} lang={q.language}><div className="qpg-question-line"><strong>{formatNumber(index+1,defaultNumbering(q.language))}</strong><span className="qpg-question-text bidi-isolate">{q.questionText}</span><span className="qpg-marks">[{q.marks}]</span></div>{q.options&&<div className="qpg-options">{q.options.map((o,j)=><div key={o.id} dir={q.direction}><span>{formatNumber(j+1,q.language==='bn'?'bangla-alpha':q.language==='ar'||q.language==='ur'?'arabic-alpha':'alpha')}</span> {o.text}</div>)}</div>}{q.subQuestions?.length&&<div className="qpg-subquestions">{q.subQuestions.map((s,i)=><div key={s.id} className="qpg-subquestion"><strong>{s.label||formatNumber(i+1,defaultNumbering(q.language))}</strong><span className="bidi-isolate">{s.text}</span><span>[{s.marks}]</span></div>)}</div>}{q.media?.map(m=><div key={m.id} className={`qpg-media qpg-align-${m.align}`}><img src={m.dataUrl} alt={m.alt} style={{width:`${Math.min(100,Math.max(25,m.width))}%`}}/></div>)}{q.table&&<div className="qpg-table-wrap"><table className="qpg-table" dir={q.table.direction}><tbody>{q.table.rows.map((row,ri)=><tr key={ri}>{row.map((cell,ci)=><td key={ci}>{cell}</td>)}</tr>)}</tbody></table></div>}</section>}
