import { useEffect, useState } from 'react'
import { Archive, BookOpen, FilePlus2, FileText, LayoutDashboard, Menu, Moon, Settings, Sun, X, ChevronRight, Search, Sparkles } from 'lucide-react'
import { LanguageSwitcher } from './components/LanguageSwitcher'
import { seedDemoData } from './storage/seed'
import { useAppStore } from './stores/appStore'
import { QuestionBank } from './components/QuestionBank'
import { PaperBuilder } from './components/PaperBuilder'
import { SavedPapers } from './components/SavedPapers'
import { AnswerKey } from './components/AnswerKey'
import { AppLanguage, getTranslation, languageMeta } from './i18n'

type Page = 'dashboard' | 'create' | 'questions' | 'papers' | 'settings'
type Theme = 'light' | 'dark' | 'system'
const nav: {id:Page; key: 'dashboard'|'createPaper'|'questionBank'|'savedPapers'|'settings'; icon: typeof LayoutDashboard}[] = [
 {id:'dashboard',key:'dashboard',icon:LayoutDashboard},{id:'create',key:'createPaper',icon:FilePlus2},{id:'questions',key:'questionBank',icon:BookOpen},{id:'papers',key:'savedPapers',icon:Archive},{id:'settings',key:'settings',icon:Settings}
]
function App() {
 const [page,setPage]=useState<Page>('dashboard'), [mobileOpen,setMobileOpen]=useState(false), [editingPaperId,setEditingPaperId]=useState<string|undefined>(), [answerPaperId,setAnswerPaperId]=useState<string|undefined>()
 const language=useAppStore(s=>s.language), theme=useAppStore(s=>s.theme), setLanguage=useAppStore(s=>s.setLanguage), setTheme=useAppStore(s=>s.setTheme)
 const questions=useAppStore(s=>s.questions), papers=useAppStore(s=>s.papers), subjects=useAppStore(s=>s.subjects), hydrate=useAppStore(s=>s.hydrate)
 const t=(key: Parameters<typeof getTranslation>[1])=>getTranslation(language,key)
 useEffect(()=>{ seedDemoData(); hydrate() },[hydrate])
 useEffect(()=>{ document.documentElement.lang=languageMeta[language].locale; document.documentElement.dir=languageMeta[language].dir },[language])
 useEffect(()=>{ const root=document.documentElement; const dark=theme==='dark'||(theme==='system'&&window.matchMedia('(prefers-color-scheme: dark)').matches); root.classList.toggle('dark',dark) },[theme])
 const navigate=(next:Page)=>{setPage(next);setMobileOpen(false)}
 return <div className="min-h-screen bg-slate-50 text-slate-950 dark:bg-slate-950 dark:text-slate-100">
  <aside className="fixed inset-y-0 left-0 z-40 hidden w-[248px] border-r border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900 lg:flex lg:flex-col"><Sidebar page={page} navigate={navigate} t={t}/></aside>
  {mobileOpen&&<div className="fixed inset-0 z-40 bg-slate-950/40 lg:hidden" onClick={()=>setMobileOpen(false)}/>}
  <aside className={`fixed inset-y-0 left-0 z-50 w-[min(86vw,320px)] border-r border-slate-200 bg-white transition-transform dark:border-slate-800 dark:bg-slate-900 lg:hidden ${mobileOpen?'translate-x-0':'-translate-x-full'}`}><div className="flex h-16 items-center justify-between border-b border-slate-200 px-4 dark:border-slate-800"><Brand/><button aria-label={t('closeMenu')} onClick={()=>setMobileOpen(false)} className="grid size-10 touch-manipulation place-items-center rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800"><X size={20}/></button></div><Sidebar page={page} navigate={navigate} t={t}/></aside>
  <div className="lg:pl-[248px]"><header className="sticky top-0 z-30 border-b border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900 dark:border-slate-800 dark:bg-slate-950/95"><div className="flex h-full items-center justify-between gap-3 px-4 sm:px-6"><div className="flex min-w-0 items-center gap-3"><button onClick={()=>setMobileOpen(true)} aria-label={t('openMenu')} className="grid size-10 touch-manipulation place-items-center rounded-lg border border-slate-200 lg:hidden dark:border-slate-800"><Menu size={20}/></button><div><h1 className="truncate text-lg font-semibold">{t(nav.find(n=>n.id===page)?.key??'dashboard')}</h1></div></div><div className="flex items-center gap-2"><button aria-label={t('search')} className="grid size-10 place-items-center rounded-xl"><Search size={19}/></button><LanguageSwitcher value={language} onChange={setLanguage}/><button aria-label="Theme" onClick={()=>setTheme(theme==='dark'?'light':'dark')} className="grid size-10 place-items-center rounded-xl">{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button></div></div></header>
  <main className="min-h-[calc(100vh-64px)] pb-24 lg:pb-8"><div className="mx-auto max-w-[1440px] p-3 sm:p-5 lg:p-7">{page==='dashboard'&&<Dashboard navigate={navigate} t={t}/>} {page==='create'&&<PaperBuilder initialPaper={editingPaperId?papers.find(p=>p.id===editingPaperId):undefined} onDone={()=>{setEditingPaperId(undefined);setPage('papers')}}/>} {page==='questions'&&<QuestionBank/>} {page==='papers'&&<SavedPapers onCreate={()=>{setEditingPaperId(undefined);navigate('create')}} onEdit={(id)=>{setEditingPaperId(id);navigate('create')}} onAnswerKey={setAnswerPaperId}/>} {answerPaperId&&<AnswerKey paper={papers.find(p=>p.id===answerPaperId)!} questions={questions} onClose={()=>setAnswerPaperId(undefined)}/>} {page==='settings'&&<SettingsPage theme={theme} setTheme={setTheme} t={t}/>}</div></main></div>
  <nav className="fixed bottom-0 left-0 right-0 z-30 border-t border-slate-200 bg-white/95 px-2 py-1.5 backdrop-blur dark:border-slate-800 dark:bg-slate-900/95 lg:hidden"><div className="mx-auto grid max-w-xl grid-cols-5">{nav.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>navigate(item.id)} className={`flex min-h-12 touch-manipulation flex-col items-center justify-center gap-0.5 rounded-lg text-[10px] ${page===item.id?'bg-slate-100 font-semibold dark:bg-slate-800':'text-slate-500'}`}><Icon size={18}/><span>{t(item.key)}</span></button>})}</div></nav>
 </div>
}
function Brand(){return <div className="flex items-center gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-950 text-white dark:bg-white dark:text-slate-950"><FileText size={20}/></div><div><div className="font-semibold">Question Builder</div><div className="text-[11px] text-slate-500">Multilingual</div></div></div>}
function Sidebar({page,navigate,t}:{page:Page;navigate:(p:Page)=>void;t:(k:Parameters<typeof getTranslation>[1])=>string}){return <div className="flex h-full flex-col px-3 py-4"><div className="border-b border-slate-100 px-2 pb-5 dark:border-slate-800"><Brand/></div><div className="mt-5 px-2 text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-400">Workspace</div><div className="mt-2 space-y-0.5">{nav.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>navigate(item.id)} className={`flex min-h-10 w-full items-center gap-3 rounded-lg px-3 text-sm ${page===item.id?'bg-slate-900 font-semibold text-white shadow-sm dark:bg-white dark:text-slate-950':'text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800'}`}><Icon size={19}/><span>{t(item.key)}</span>{page===item.id&&<ChevronRight className="ml-auto" size={16}/>}</button>})}</div><div className="mt-auto border-t border-slate-100 pt-4 dark:border-slate-800"><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><div className="flex items-center gap-2"><Sparkles size={16}/><span className="text-xs font-semibold">Multilingual</span></div><p className="mt-1 text-[11px] leading-5 text-slate-500">বাংলা · English · العربية · اردو</p></div></div></div>}
function Dashboard({navigate,t}:{navigate:(p:Page)=>void;t:(k:Parameters<typeof getTranslation>[1])=>string}){const {questions,papers,subjects}=useAppStore(); const stats=[[t('totalQuestions'),String(questions.length)],[t('totalPapers'),String(papers.length)],[t('drafts'),String(papers.filter(p=>p.status==='draft').length)],[t('subjects'),String(subjects.length)]];return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-slate-500">{t('welcome')}</p><h2 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">{t('whatToCreate')}</h2></div><button onClick={()=>navigate('create')} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 text-sm font-medium text-white dark:bg-white dark:text-slate-950"><FilePlus2 size={18}/>{t('createPaper')}</button></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map(([label,value])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>)}</div><div className="grid gap-4 md:grid-cols-3"><Action title={t('addQuestion')} text={t('questionBank')} icon={BookOpen} onClick={()=>navigate('questions')}/><Action title={t('createNewPaper')} text={t('examInformation')} icon={FilePlus2} onClick={()=>navigate('create')}/><Action title={t('settings')} text={t('appearance')} icon={Settings} onClick={()=>navigate('settings')}/></div></div>}
function Action({title,text,icon:Icon,onClick}:{title:string;text:string;icon:typeof BookOpen;onClick:()=>void}){return <button onClick={onClick} className="text-left rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><Icon size={20}/><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-1 text-sm text-slate-500">{text}</p></button>}
function EmptyPage({icon:Icon,title,action}:{icon:typeof BookOpen;title:string;action:string}){return <div className="grid min-h-[60vh] place-items-center"><div className="text-center"><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-slate-100 dark:bg-slate-900"><Icon/></div><h2 className="mt-4 font-semibold">{title}</h2><button className="mt-4 min-h-11 rounded-xl bg-slate-950 px-5 text-sm font-medium text-white dark:bg-white dark:text-slate-950">{action}</button></div></div>}
function CreatePage({t}:{t:(k:Parameters<typeof getTranslation>[1])=>string}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">{t('createPaper')}</h2><div className="mt-5 grid grid-cols-5 gap-2 text-center text-xs">{(['examInformation','questions','arrangement','design','preview'] as const).map((k,i)=><div key={k} className="rounded-xl bg-slate-100 p-3 dark:bg-slate-800"><span className="font-semibold">{i+1}</span><p className="mt-1">{t(k)}</p></div>)}</div></div>}
function SettingsPage({theme,setTheme,t}:{theme:Theme;setTheme:(t:Theme)=>void;t:(k:Parameters<typeof getTranslation>[1])=>string}){return <div className="max-w-3xl"><div className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">{t('appearance')}</h2><div className="mt-4 flex flex-wrap gap-2">{(['light','dark','system'] as Theme[]).map(x=><button key={x} onClick={()=>setTheme(x)} className={`min-h-11 rounded-xl border px-4 text-sm ${theme===x?'border-slate-950 bg-slate-950 text-white dark:border-white dark:bg-white dark:text-slate-950':'border-slate-200 dark:border-slate-700'}`}>{t(x)}</button>)}</div></div></div>}
export default App
